// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: unreal_common.proto

package unrealpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FVector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *FVector) Reset() {
	*x = FVector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unreal_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FVector) ProtoMessage() {}

func (x *FVector) ProtoReflect() protoreflect.Message {
	mi := &file_unreal_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FVector.ProtoReflect.Descriptor instead.
func (*FVector) Descriptor() ([]byte, []int) {
	return file_unreal_common_proto_rawDescGZIP(), []int{0}
}

func (x *FVector) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FVector) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FVector) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type SceneComponentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Marks that the state should be removed from the containing map
	Removed          bool     `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	RelativeLocation *FVector `protobuf:"bytes,2,opt,name=relativeLocation,proto3" json:"relativeLocation,omitempty"`
	RelativeRotation *FVector `protobuf:"bytes,3,opt,name=relativeRotation,proto3" json:"relativeRotation,omitempty"`
	RelativeScale    *FVector `protobuf:"bytes,4,opt,name=relativeScale,proto3" json:"relativeScale,omitempty"`
	IsVisible        bool     `protobuf:"varint,5,opt,name=isVisible,proto3" json:"isVisible,omitempty"`
	AttachSocketName string   `protobuf:"bytes,6,opt,name=attachSocketName,proto3" json:"attachSocketName,omitempty"`
}

func (x *SceneComponentState) Reset() {
	*x = SceneComponentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unreal_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneComponentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneComponentState) ProtoMessage() {}

func (x *SceneComponentState) ProtoReflect() protoreflect.Message {
	mi := &file_unreal_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneComponentState.ProtoReflect.Descriptor instead.
func (*SceneComponentState) Descriptor() ([]byte, []int) {
	return file_unreal_common_proto_rawDescGZIP(), []int{1}
}

func (x *SceneComponentState) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *SceneComponentState) GetRelativeLocation() *FVector {
	if x != nil {
		return x.RelativeLocation
	}
	return nil
}

func (x *SceneComponentState) GetRelativeRotation() *FVector {
	if x != nil {
		return x.RelativeRotation
	}
	return nil
}

func (x *SceneComponentState) GetRelativeScale() *FVector {
	if x != nil {
		return x.RelativeScale
	}
	return nil
}

func (x *SceneComponentState) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *SceneComponentState) GetAttachSocketName() string {
	if x != nil {
		return x.AttachSocketName
	}
	return ""
}

var File_unreal_common_proto protoreflect.FileDescriptor

var file_unreal_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x6c, 0x70, 0x62, 0x22,
	0x33, 0x0a, 0x07, 0x46, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x7a, 0x22, 0xb0, 0x02, 0x0a, 0x13, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x3d, 0x0a, 0x10, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x6c, 0x70, 0x62, 0x2e, 0x46, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x10, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x10, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x6c, 0x70, 0x62, 0x2e, 0x46, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x10, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x53, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x6c, 0x70, 0x62, 0x2e, 0x46, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0d,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x53, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x64, 0x2e, 0x63, 0x6c, 0x65, 0x77, 0x63, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x6e, 0x72,
	0x65, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unreal_common_proto_rawDescOnce sync.Once
	file_unreal_common_proto_rawDescData = file_unreal_common_proto_rawDesc
)

func file_unreal_common_proto_rawDescGZIP() []byte {
	file_unreal_common_proto_rawDescOnce.Do(func() {
		file_unreal_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_unreal_common_proto_rawDescData)
	})
	return file_unreal_common_proto_rawDescData
}

var file_unreal_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unreal_common_proto_goTypes = []interface{}{
	(*FVector)(nil),             // 0: unrealpb.FVector
	(*SceneComponentState)(nil), // 1: unrealpb.SceneComponentState
}
var file_unreal_common_proto_depIdxs = []int32{
	0, // 0: unrealpb.SceneComponentState.relativeLocation:type_name -> unrealpb.FVector
	0, // 1: unrealpb.SceneComponentState.relativeRotation:type_name -> unrealpb.FVector
	0, // 2: unrealpb.SceneComponentState.relativeScale:type_name -> unrealpb.FVector
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_unreal_common_proto_init() }
func file_unreal_common_proto_init() {
	if File_unreal_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unreal_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FVector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unreal_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneComponentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unreal_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unreal_common_proto_goTypes,
		DependencyIndexes: file_unreal_common_proto_depIdxs,
		MessageInfos:      file_unreal_common_proto_msgTypes,
	}.Build()
	File_unreal_common_proto = out.File
	file_unreal_common_proto_rawDesc = nil
	file_unreal_common_proto_goTypes = nil
	file_unreal_common_proto_depIdxs = nil
}
