// Generated by ChanneldUE's replication code generator. DO NOT EDIT.

package main

import (
	"github.com/metaworking/channeld/examples/channeld-ue-tps/tpspb"
	"github.com/metaworking/channeld/pkg/channeld"
	"github.com/metaworking/channeld/pkg/channeldpb"
)

func InitChannelDataTypes() {
	channeld.RegisterChannelDataType(channeldpb.ChannelType_GLOBAL, &tpspb.TestRepChannelData{})
}
