FROM golang:1.18.8

COPY . /channeld

WORKDIR /channeld/examples/channeld-ue-tps

ENV GOPROXY="https://goproxy.io"
RUN go get -d -v ./...
RUN go install -v ./...
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o . ./...
RUN apt-get -y update && apt-get -y install ethtool

COPY ./config /channeld/examples/channeld-ue-tps/config

EXPOSE 12108
EXPOSE 11288

ENTRYPOINT ["./channeld-ue-tps"]