apiVersion: v1
kind: Service
metadata:
  namespace: channeld
  labels:
    io.kompose.service: kooola-channeld-chat
  name: kooola-channeld-chat
spec:
  ports:
    - name: "client"
      port: 12108
      targetPort: client-port
  selector:
    io.kompose.service: kooola-channeld-chat
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  namespace: channeld
  labels:
    io.kompose.service: kooola-channeld-chat
  name: kooola-channeld-chat-server
spec:
  ports:
    - name: "server"
      port: 11288
      targetPort: server-port
  selector:
    io.kompose.service: kooola-channeld-chat