// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.3
// source: channeld.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelType int32

const (
	ChannelType_UNKNOWN  ChannelType = 0
	ChannelType_GLOBAL   ChannelType = 1 // Default channel. Any message without ChannelId specified will be sent to this channel. All connections join this channel.
	ChannelType_PRIVATE  ChannelType = 2 // Per-connection channel. Useful to store the user data and subscribe the client to the data update.
	ChannelType_SUBWORLD ChannelType = 3 // A game "room" in a session-based game, or a level in an MMORPG. Subworlds are spatially divided thus the interests are isolated.
	ChannelType_SPATIAL  ChannelType = 4 // Spatial channels are spatailly connected. Using this channel to implement a seamless open world.
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "UNKNOWN",
		1: "GLOBAL",
		2: "PRIVATE",
		3: "SUBWORLD",
		4: "SPATIAL",
	}
	ChannelType_value = map[string]int32{
		"UNKNOWN":  0,
		"GLOBAL":   1,
		"PRIVATE":  2,
		"SUBWORLD": 3,
		"SPATIAL":  4,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_channeld_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_channeld_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_INVALID MessageType = 0
	MessageType_AUTH    MessageType = 1
	//AUTH_RESULT = 2;
	MessageType_CREATE_CHANNEL       MessageType = 3
	MessageType_REMOVE_CHANNEL       MessageType = 4
	MessageType_SUB_TO_CHANNEL       MessageType = 5
	MessageType_UNSUB_TO_CHANNEL     MessageType = 6
	MessageType_CHANNEL_DATA_GLOBAL  MessageType = 11
	MessageType_CHANNEL_DATA_SPATIAL MessageType = 14
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "INVALID",
		1:  "AUTH",
		3:  "CREATE_CHANNEL",
		4:  "REMOVE_CHANNEL",
		5:  "SUB_TO_CHANNEL",
		6:  "UNSUB_TO_CHANNEL",
		11: "CHANNEL_DATA_GLOBAL",
		14: "CHANNEL_DATA_SPATIAL",
	}
	MessageType_value = map[string]int32{
		"INVALID":              0,
		"AUTH":                 1,
		"CREATE_CHANNEL":       3,
		"REMOVE_CHANNEL":       4,
		"SUB_TO_CHANNEL":       5,
		"UNSUB_TO_CHANNEL":     6,
		"CHANNEL_DATA_GLOBAL":  11,
		"CHANNEL_DATA_SPATIAL": 14,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_channeld_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_channeld_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{1}
}

type AuthResultMessage_AuthResult int32

const (
	AuthResultMessage_SUCCESSFUL  AuthResultMessage_AuthResult = 0
	AuthResultMessage_INVALID_PIT AuthResultMessage_AuthResult = 1
	AuthResultMessage_INVALID_L   AuthResultMessage_AuthResult = 2
)

// Enum value maps for AuthResultMessage_AuthResult.
var (
	AuthResultMessage_AuthResult_name = map[int32]string{
		0: "SUCCESSFUL",
		1: "INVALID_PIT",
		2: "INVALID_L",
	}
	AuthResultMessage_AuthResult_value = map[string]int32{
		"SUCCESSFUL":  0,
		"INVALID_PIT": 1,
		"INVALID_L":   2,
	}
)

func (x AuthResultMessage_AuthResult) Enum() *AuthResultMessage_AuthResult {
	p := new(AuthResultMessage_AuthResult)
	*p = x
	return p
}

func (x AuthResultMessage_AuthResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthResultMessage_AuthResult) Descriptor() protoreflect.EnumDescriptor {
	return file_channeld_proto_enumTypes[2].Descriptor()
}

func (AuthResultMessage_AuthResult) Type() protoreflect.EnumType {
	return &file_channeld_proto_enumTypes[2]
}

func (x AuthResultMessage_AuthResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthResultMessage_AuthResult.Descriptor instead.
func (AuthResultMessage_AuthResult) EnumDescriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{1, 0}
}

type AuthMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerIdentifierToken string `protobuf:"bytes,1,opt,name=playerIdentifierToken,proto3" json:"playerIdentifierToken,omitempty"`
	LoginToken            string `protobuf:"bytes,2,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{0}
}

func (x *AuthMessage) GetPlayerIdentifierToken() string {
	if x != nil {
		return x.PlayerIdentifierToken
	}
	return ""
}

func (x *AuthMessage) GetLoginToken() string {
	if x != nil {
		return x.LoginToken
	}
	return ""
}

type AuthResultMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result AuthResultMessage_AuthResult `protobuf:"varint,1,opt,name=result,proto3,enum=channeld.AuthResultMessage_AuthResult" json:"result,omitempty"`
}

func (x *AuthResultMessage) Reset() {
	*x = AuthResultMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResultMessage) ProtoMessage() {}

func (x *AuthResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResultMessage.ProtoReflect.Descriptor instead.
func (*AuthResultMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResultMessage) GetResult() AuthResultMessage_AuthResult {
	if x != nil {
		return x.Result
	}
	return AuthResultMessage_SUCCESSFUL
}

type CreateChannelMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelType ChannelType `protobuf:"varint,1,opt,name=channelType,proto3,enum=channeld.ChannelType" json:"channelType,omitempty"`
}

func (x *CreateChannelMessage) Reset() {
	*x = CreateChannelMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelMessage) ProtoMessage() {}

func (x *CreateChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelMessage.ProtoReflect.Descriptor instead.
func (*CreateChannelMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChannelMessage) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_UNKNOWN
}

type RemoveChannelMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveChannelMessage) Reset() {
	*x = RemoveChannelMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChannelMessage) ProtoMessage() {}

func (x *RemoveChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChannelMessage.ProtoReflect.Descriptor instead.
func (*RemoveChannelMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{3}
}

type SubscribedToChannelsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId     uint32   `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`
	ChannelIds []uint32 `protobuf:"varint,2,rep,packed,name=channelIds,proto3" json:"channelIds,omitempty"`
}

func (x *SubscribedToChannelsMessage) Reset() {
	*x = SubscribedToChannelsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribedToChannelsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribedToChannelsMessage) ProtoMessage() {}

func (x *SubscribedToChannelsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribedToChannelsMessage.ProtoReflect.Descriptor instead.
func (*SubscribedToChannelsMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribedToChannelsMessage) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *SubscribedToChannelsMessage) GetChannelIds() []uint32 {
	if x != nil {
		return x.ChannelIds
	}
	return nil
}

type UnsubscribedToChannelsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId     uint32   `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`
	ChannelIds []uint32 `protobuf:"varint,2,rep,packed,name=channelIds,proto3" json:"channelIds,omitempty"`
}

func (x *UnsubscribedToChannelsMessage) Reset() {
	*x = UnsubscribedToChannelsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribedToChannelsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribedToChannelsMessage) ProtoMessage() {}

func (x *UnsubscribedToChannelsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribedToChannelsMessage.ProtoReflect.Descriptor instead.
func (*UnsubscribedToChannelsMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribedToChannelsMessage) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *UnsubscribedToChannelsMessage) GetChannelIds() []uint32 {
	if x != nil {
		return x.ChannelIds
	}
	return nil
}

type GlobalChannelDataMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title         string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ClientConnNum uint32 `protobuf:"varint,2,opt,name=clientConnNum,proto3" json:"clientConnNum,omitempty"`
}

func (x *GlobalChannelDataMessage) Reset() {
	*x = GlobalChannelDataMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalChannelDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalChannelDataMessage) ProtoMessage() {}

func (x *GlobalChannelDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalChannelDataMessage.ProtoReflect.Descriptor instead.
func (*GlobalChannelDataMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{6}
}

func (x *GlobalChannelDataMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GlobalChannelDataMessage) GetClientConnNum() uint32 {
	if x != nil {
		return x.ClientConnNum
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{7}
}

func (x *Location) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Location) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Location) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type SpatialEntityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loc *Location `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
}

func (x *SpatialEntityInfo) Reset() {
	*x = SpatialEntityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpatialEntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatialEntityInfo) ProtoMessage() {}

func (x *SpatialEntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatialEntityInfo.ProtoReflect.Descriptor instead.
func (*SpatialEntityInfo) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{8}
}

func (x *SpatialEntityInfo) GetLoc() *Location {
	if x != nil {
		return x.Loc
	}
	return nil
}

type SpatialChannelDataMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities map[uint32]*SpatialEntityInfo `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SpatialChannelDataMessage) Reset() {
	*x = SpatialChannelDataMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channeld_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpatialChannelDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatialChannelDataMessage) ProtoMessage() {}

func (x *SpatialChannelDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channeld_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatialChannelDataMessage.ProtoReflect.Descriptor instead.
func (*SpatialChannelDataMessage) Descriptor() ([]byte, []int) {
	return file_channeld_proto_rawDescGZIP(), []int{9}
}

func (x *SpatialChannelDataMessage) GetEntities() map[uint32]*SpatialEntityInfo {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_channeld_proto protoreflect.FileDescriptor

var file_channeld_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64, 0x22, 0x63, 0x0a, 0x0b, 0x41, 0x75,
	0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x91, 0x01, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3c, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x46, 0x55,
	0x4c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50,
	0x49, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x4c, 0x10, 0x02, 0x22, 0x4f, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x1b,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x54, 0x6f, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x49, 0x64, 0x73, 0x22, 0x57, 0x0a, 0x1d, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x64, 0x54, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x56, 0x0a, 0x18,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x4e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x4e, 0x75, 0x6d, 0x22, 0x34, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x22, 0x39, 0x0a, 0x11, 0x53, 0x70,
	0x61, 0x74, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x24, 0x0a, 0x03, 0x6c, 0x6f, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x03, 0x6c, 0x6f, 0x63, 0x22, 0xc4, 0x01, 0x0a, 0x19, 0x53, 0x70, 0x61, 0x74, 0x69, 0x61,
	0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x4d, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64,
	0x2e, 0x53, 0x70, 0x61, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x1a, 0x58, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x64, 0x2e,
	0x53, 0x70, 0x61, 0x74, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x4e, 0x0a, 0x0b,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4c, 0x4f, 0x42,
	0x41, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x55, 0x42, 0x57, 0x4f, 0x52, 0x4c, 0x44, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x50, 0x41, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x04, 0x2a, 0xa9, 0x01, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x55, 0x54,
	0x48, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x4d, 0x4f, 0x56,
	0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x53,
	0x55, 0x42, 0x5f, 0x54, 0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x05, 0x12,
	0x14, 0x0a, 0x10, 0x55, 0x4e, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e,
	0x4e, 0x45, 0x4c, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c,
	0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x47, 0x4c, 0x4f, 0x42, 0x41, 0x4c, 0x10, 0x0b, 0x12, 0x18,
	0x0a, 0x14, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x53,
	0x50, 0x41, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x0e, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_channeld_proto_rawDescOnce sync.Once
	file_channeld_proto_rawDescData = file_channeld_proto_rawDesc
)

func file_channeld_proto_rawDescGZIP() []byte {
	file_channeld_proto_rawDescOnce.Do(func() {
		file_channeld_proto_rawDescData = protoimpl.X.CompressGZIP(file_channeld_proto_rawDescData)
	})
	return file_channeld_proto_rawDescData
}

var file_channeld_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_channeld_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_channeld_proto_goTypes = []interface{}{
	(ChannelType)(0),                      // 0: channeld.ChannelType
	(MessageType)(0),                      // 1: channeld.MessageType
	(AuthResultMessage_AuthResult)(0),     // 2: channeld.AuthResultMessage.AuthResult
	(*AuthMessage)(nil),                   // 3: channeld.AuthMessage
	(*AuthResultMessage)(nil),             // 4: channeld.AuthResultMessage
	(*CreateChannelMessage)(nil),          // 5: channeld.CreateChannelMessage
	(*RemoveChannelMessage)(nil),          // 6: channeld.RemoveChannelMessage
	(*SubscribedToChannelsMessage)(nil),   // 7: channeld.SubscribedToChannelsMessage
	(*UnsubscribedToChannelsMessage)(nil), // 8: channeld.UnsubscribedToChannelsMessage
	(*GlobalChannelDataMessage)(nil),      // 9: channeld.GlobalChannelDataMessage
	(*Location)(nil),                      // 10: channeld.Location
	(*SpatialEntityInfo)(nil),             // 11: channeld.SpatialEntityInfo
	(*SpatialChannelDataMessage)(nil),     // 12: channeld.SpatialChannelDataMessage
	nil,                                   // 13: channeld.SpatialChannelDataMessage.EntitiesEntry
}
var file_channeld_proto_depIdxs = []int32{
	2,  // 0: channeld.AuthResultMessage.result:type_name -> channeld.AuthResultMessage.AuthResult
	0,  // 1: channeld.CreateChannelMessage.channelType:type_name -> channeld.ChannelType
	10, // 2: channeld.SpatialEntityInfo.loc:type_name -> channeld.Location
	13, // 3: channeld.SpatialChannelDataMessage.entities:type_name -> channeld.SpatialChannelDataMessage.EntitiesEntry
	11, // 4: channeld.SpatialChannelDataMessage.EntitiesEntry.value:type_name -> channeld.SpatialEntityInfo
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_channeld_proto_init() }
func file_channeld_proto_init() {
	if File_channeld_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_channeld_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResultMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChannelMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveChannelMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribedToChannelsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribedToChannelsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalChannelDataMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpatialEntityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channeld_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpatialChannelDataMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_channeld_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_channeld_proto_goTypes,
		DependencyIndexes: file_channeld_proto_depIdxs,
		EnumInfos:         file_channeld_proto_enumTypes,
		MessageInfos:      file_channeld_proto_msgTypes,
	}.Build()
	File_channeld_proto = out.File
	file_channeld_proto_rawDesc = nil
	file_channeld_proto_goTypes = nil
	file_channeld_proto_depIdxs = nil
}
